#!/bin/bash

make
./copy-res
./oasm-as -i examples/ostdlib.oasm -dt -sc -SC -SL
./oasm-as -i examples/test-lib.oasm -dt -sc -SC -SL
./oasm-as -i examples/use-lib.oasm -dt -sc -SC -I ostd -L examples -lsd test-lib -lsd ostdlib
./vm use-lib
